# Generated by Django 4.1.1 on 2022-09-19 16:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefonoCliente', models.IntegerField()),
                ('nombreCliente', models.CharField(max_length=100)),
                ('nitCliente', models.CharField(max_length=20)),
                ('direccionCliente', models.CharField(max_length=100)),
                ('correoCliente', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaSiembra', models.DateField()),
                ('fechaCosecha', models.DateField()),
                ('cantidadCosecha', models.IntegerField()),
                ('observacCultivo', models.CharField(max_length=300)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreFinca', models.CharField(max_length=100)),
                ('nombreGerente', models.CharField(max_length=100)),
                ('apellidoGerente', models.CharField(max_length=100, null=True)),
                ('nitFinca', models.IntegerField()),
                ('correoGerente', models.CharField(max_length=100)),
                ('cedulaGerente', models.CharField(max_length=100)),
                ('ubicacionFinca', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InsumoFinca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existenciaInsumo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valorUnitarioInsumo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGerente.finca')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.insumo')),
                ('unidadmedida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.unidadmedida')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existenciaProducto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripProducto', models.CharField(max_length=100)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGerente.finca')),
                ('unidadMedida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.unidadmedida')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numFactura', models.CharField(max_length=15)),
                ('fechaventa', models.DateField(default=datetime.date.today)),
                ('cantidadVenta', models.IntegerField()),
                ('observacVenta', models.CharField(max_length=300)),
                ('valorTotalVentas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGerente.cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGerente.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefonoTrabajador', models.CharField(max_length=20)),
                ('nombreTrabajador', models.CharField(max_length=100)),
                ('nitTrabajador', models.IntegerField()),
                ('emailTrabajador', models.CharField(max_length=100)),
                ('costoHoraTrabajador', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rol', models.IntegerField(default=0)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGerente.finca')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacLote', models.CharField(max_length=300)),
                ('descripLote', models.CharField(max_length=100)),
                ('areaLote', models.IntegerField()),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGerente.finca')),
                ('unidadMedida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.unidadmedida')),
            ],
        ),
        migrations.CreateModel(
            name='InsumosLabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadUsadaInsumo', models.IntegerField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGerente.cultivo')),
                ('insumoFinca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGerente.insumofinca')),
            ],
        ),
        migrations.CreateModel(
            name='Indirecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaPago', models.DateField()),
                ('numFactura', models.CharField(max_length=15)),
                ('observacPago', models.CharField(max_length=200)),
                ('valorPagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGerente.finca')),
            ],
        ),
        migrations.CreateModel(
            name='HoraTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacLabor', models.CharField(max_length=300)),
                ('tipoTrabajo', models.CharField(max_length=300)),
                ('fechaLabor', models.DateField()),
                ('duracionLabor', models.IntegerField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('categHora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.categhora')),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGerente.cultivo')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGerente.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='EquipoFinca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existenciaEquipo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valorUnitarioEquipo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deprecEquipo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.equipo')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGerente.finca')),
            ],
        ),
        migrations.AddField(
            model_name='cultivo',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGerente.lote'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGerente.producto'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='unidadMedida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.unidadmedida'),
        ),
        migrations.CreateModel(
            name='CompraInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadCompraInsumo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechaCompraInsumo', models.DateField()),
                ('numFactura', models.CharField(max_length=15)),
                ('valorCompraInsumo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.insumo')),
                ('insumoFinca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGerente.insumofinca')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='CompraEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCompraEquipo', models.DateField()),
                ('numFactura', models.CharField(max_length=15)),
                ('cantidadCompraEquipo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.equipo')),
                ('equipoFinca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGerente.equipofinca')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.proveedor')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='finca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGerente.finca'),
        ),
    ]
