# Generated by Django 4.1.1 on 2022-11-22 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appGerente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compraequipo',
            options={'verbose_name_plural': 'Compra de equipos'},
        ),
        migrations.AlterModelOptions(
            name='comprainsumo',
            options={'verbose_name_plural': 'Compra de insumos'},
        ),
        migrations.AlterModelOptions(
            name='equipofinca',
            options={'verbose_name_plural': 'Equipo de fincas'},
        ),
        migrations.AlterModelOptions(
            name='horatrabajo',
            options={'verbose_name_plural': 'Horas de trabajo'},
        ),
        migrations.AlterModelOptions(
            name='insumofinca',
            options={'verbose_name_plural': 'Insumos de finca'},
        ),
        migrations.AlterModelOptions(
            name='insumoslabor',
            options={'verbose_name_plural': 'Insumos de labores'},
        ),
        migrations.AlterModelOptions(
            name='trabajador',
            options={'verbose_name_plural': 'Trabajadores'},
        ),
    ]
