# Generated by Django 4.1.1 on 2022-11-28 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appGerente', '0002_alter_compraequipo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indirecto',
            options={'verbose_name_plural': 'Costos indirectos'},
        ),
    ]
