# Generated by Django 4.1.1 on 2022-12-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGerente', '0003_alter_indirecto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipofinca',
            name='descripEquipoFinca',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
