# Generated by Django 4.1.1 on 2022-12-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGerente', '0004_equipofinca_descripequipofinca'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumofinca',
            name='descripInsumoFinca',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
