# Generated by Django 4.1.1 on 2022-12-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGerente', '0005_insumofinca_descripinsumofinca'),
    ]

    operations = [
        migrations.AddField(
            model_name='compraequipo',
            name='valorCompraEquipo',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
