# Generated by Django 4.1.1 on 2022-12-11 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appGerente', '0006_compraequipo_valorcompraequipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insumoslabor',
            options={'verbose_name_plural': 'Labores de Insumos'},
        ),
        migrations.CreateModel(
            name='EquiposLabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadUsadaEquipo', models.IntegerField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGerente.cultivo')),
                ('equipoFinca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGerente.equipofinca')),
            ],
            options={
                'verbose_name_plural': 'Labores de Equipos',
            },
        ),
    ]
