# Generated by Django 4.1.1 on 2022-09-19 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategHora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recargo', models.CharField(max_length=100)),
                ('descripCategHora', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Categoria de Horas',
            },
        ),
        migrations.CreateModel(
            name='CategMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripCategMaterial', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categoria Materiales ',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefonoProveedor', models.IntegerField()),
                ('nombreProveedor', models.CharField(max_length=100)),
                ('nitProvedor', models.CharField(max_length=20)),
                ('direccionProveedor', models.CharField(max_length=100)),
                ('correoProveedor', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripUnidadMedida', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Unidades Medidas',
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripInsumo', models.CharField(max_length=100)),
                ('categMaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.categmaterial')),
                ('unidadMedida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.unidadmedida')),
            ],
            options={
                'verbose_name_plural': 'Insumos',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripEquipo', models.CharField(max_length=100)),
                ('categMaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.categmaterial')),
            ],
            options={
                'verbose_name_plural': 'Equipos',
            },
        ),
    ]
